name: Build package
description: Build package
inputs:
  package:
    default: common
    description: Choose a package to build

runs:
  using: composite
  steps:
    - name: Build ${{ inputs.package}}
      run: npm run build
      shell: bash
      working-directory: packages/${{ inputs.package }}
